---

# - name: Update packages
#   pacman: upgrade=yes update_cache=yes

# as a reminder pacman -Qqe > package_list.txt
- name: Install libraries using pacman
  pacman: name={{ item }} state=latest
  sudo: true
  with_items:
     - ack
     - clang
     - emacs
     - feh
     - i3-wm
     - i3lock
     - i3status
     - irssi
     - lxappearance
     - mopidy
     - mpc
     - mutt
     - ncmpcpp
     - network-manager-applet
     - nitrogen
     - nodejs
     - npm
     - ranger
     - rxvt-unicode
     - screenfetch
     - tar
     - terminator
     - terminus-font
     - tig
     - tmux
     - tree
     - unrar
     - unzip
     - upower
     - vim
     - w3m
     - weechat
     - xclip
     - xorg-server
     - xorg-xinit
     - youtube-dl
     - zsh

- name: Change shell to ZSH
  sudo: true
  user: shell=/bin/zsh name={{ ansible_ssh_user }}

- name: Set up Arch specific ~/home
  file: src=~/dotfiles/home/{{ item }}
        dest=~/{{ item }}
        state=link
        force=yes
  with_items:
    - .i3

- name: Set up .config directory
  file: src=~/dotfiles/config/{{ item }}
        dest=~/.config/{{ item }}
        state=link
        force=yes
  with_items:
    - lemonbar
    - terminator
