---

# - name: Update packages
#   pacman: upgrade=yes update_cache=yes

# as a reminder pacman -Qqe > package_list.txt
- name: Install libraries using pacman
  pacman: name={{ item }} state=latest
  sudo: true
  with_items:
    - accountsservice
    - ack
    - acpi
    - alex
    - alsa-utils
    - antergos-gnome-defaults-list
    - antergos-keyring
    - antergos-mirrorlist
    - antergos-wallpapers
    - autoconf
    - automake
    - b43-fwcutter
    - baobab
    - bash
    - bash-completion
    - bijiben
    - bind-tools
    - binutils
    - bison
    - bleachbit
    - blueman
    - bluez-utils
    - bzip2
    - bzr
    - cabal-install
    - cairo-infinality-ultimate
    - cdrkit
    - chromium-pepper-flash
    - clang
    - cmake
    - cmatrix
    - conky
    - coreutils
    - crda
    - cronie
    - cryptsetup
    - cups
    - cups-pk-helper
    - device-mapper
    - dhcpcd
    - diffutils
    - dina-font
    - dosfstools
    - dropbox
    - e2fsprogs
    - emacs
    - eog
    - evince
    - fakeroot
    - feh
    - festival
    - file
    - file-roller
    - filesystem
    - filezilla
    - findutils
    - firefox
    - flex
    - fontconfig-infinality-ultimate
    - freetype2-infinality-ultimate
    - gawk
    - gcc
    - gcc-libs
    - gdb
    - geary
    - gedit
    - gettext
    - gimp
    - git
    - gitg
    - glibc
    - gnome-backgrounds
    - gnome-bluetooth
    - gnome-calculator
    - gnome-calendar
    - gnome-contacts
    - gnome-control-center
    - gnome-disk-utility
    - gnome-documents
    - gnome-font-viewer
    - gnome-keyring
    - gnome-logs
    - gnome-maps
    - gnome-music
    - gnome-photos
    - gnome-screenshot
    - gnome-shell
    - gnome-shell-extension-dash-to-dock
    - gnome-shell-extension-status-menu-buttons
    - gnome-shell-extensions
    - gnome-sound-recorder
    - gnome-system-monitor
    - gnome-themes-standard
    - gnome-tweak-tool
    - gnome-weather
    - grep
    - groff
    - grub
    - gsfonts
    - gst-libav
    - gst-plugins-bad
    - gst-plugins-base
    - gst-plugins-good
    - gst-plugins-ugly
    - gstreamer-vaapi
    - gstreamer0.10-bad-plugins
    - gstreamer0.10-base-plugins
    - gstreamer0.10-ffmpeg
    - gstreamer0.10-good-plugins
    - gstreamer0.10-ugly-plugins
    - gtk2-perl
    - gufw
    - gvfs-mtp
    - gvfs-smb
    - gzip
    - hamster-time-tracker
    - happy
    - haveged
    - hicolor-icon-theme
    - hplip
    - htop
    - hunspell-en
    - i3-wm
    - i3lock
    - i3status
    - inetutils
    - inkscape
    - iproute2
    - iputils
    - ipw2100-fw
    - ipw2200-fw
    - ipython
    - irssi
    - jfsutils
    - less
    - lib32-mesa
    - lib32-mesa-libgl
    - lib32-xcb-util
    - libcryptui
    - libdvdcss
    - libgnomeui
    - libreoffice-fresh
    - libtool
    - libtxc_dxtn
    - libva-intel-driver
    - licenses
    - light-locker
    - light-locker-settings
    - lightdm
    - lightdm-webkit-theme-antergos
    - linux
    - logrotate
    - lvm2
    - lxappearance
    - m4
    - make
    - man-db
    - man-pages
    - mariadb
    - mdadm
    - mednafen
    - meld
    - mesa
    - mesa-vdpau
    - modemmanager
    - mopidy
    - mpc
    - mutt
    - nano
    - nautilus
    - ncmpcpp
    - net-tools
    - netctl
    - network-manager-applet
    - networkmanager-openvpn
    - networkmanager-pptp
    - nitrogen
    - nodejs
    - npm
    - ntfs-3g
    - ntp
    - numix-frost-themes
    - numix-icon-theme
    - numix-icon-theme-square
    - offlineimap
    - openssh
    - orca
    - os-prober
    - pacman
    - pamac
    - patch
    - pavucontrol
    - pciutils
    - pcmciautils
    - perl
    - php-composer
    - pidgin
    - pkg-config
    - pkgfile
    - procps-ng
    - profanity
    - psmisc
    - pulseaudio-alsa
    - pulseaudio-bluetooth
    - pulseaudio-equalizer
    - pulseaudio-gconf
    - pulseaudio-jack
    - pulseaudio-lirc
    - pulseaudio-xen
    - pulseaudio-zeroconf
    - python-httplib2
    - python-pip
    - python-urllib3
    - python-virtualenv
    - python2-httplib2
    - python2-librabbitmq
    - python2-ndg-httpsclient
    - python2-poster
    - python2-urllib3
    - python2-virtualenv
    - python2-xlib
    - ranger
    - redshift
    - reiserfsprogs
    - rng-tools
    - rxvt-unicode
    - s-nail
    - screen
    - screenfetch
    - scrot
    - seahorse
    - sed
    - shadow
    - skype
    - splix
    - sudo
    - sysfsutils
    - system-config-printer
    - systemd-sysvcompat
    - tamsyn-font
    - tar
    - terminator
    - terminus-font
    - texinfo
    - tig
    - tmux
    - tokumx
    - totem
    - transmission-cli
    - transmission-gtk
    - tree
    - ttf-bitstream-vera
    - ttf-dejavu
    - ttf-freefont
    - ttf-google-fonts
    - ttf-liberation
    - ufw
    - unrar
    - unzip
    - upower
    - usb_modeswitch
    - usbutils
    - util-linux
    - vi
    - vim
    - volumeicon
    - w3m
    - weechat
    - wget
    - which
    - whois
    - wireless_tools
    - wpa_actiond
    - xclip
    - xcompmgr
    - xdg-user-dirs-gtk
    - xdotool
    - xf86-input-synaptics
    - xf86-video-fbdev
    - xf86-video-intel
    - xf86-video-vesa
    - xfsprogs
    - xorg-bdftopcf
    - xorg-font-util
    - xorg-fonts-encodings
    - xorg-iceauth
    - xorg-luit
    - xorg-mkfontdir
    - xorg-mkfontscale
    - xorg-server
    - xorg-server-utils
    - xorg-sessreg
    - xorg-setxkbmap
    - xorg-smproxy
    - xorg-x11perf
    - xorg-xauth
    - xorg-xbacklight
    - xorg-xcmsdb
    - xorg-xcursorgen
    - xorg-xdpyinfo
    - xorg-xdriinfo
    - xorg-xev
    - xorg-xgamma
    - xorg-xhost
    - xorg-xinit
    - xorg-xinput
    - xorg-xkbcomp
    - xorg-xkbevd
    - xorg-xkbutils
    - xorg-xkill
    - xorg-xlsatoms
    - xorg-xlsclients
    - xorg-xmodmap
    - xorg-xpr
    - xorg-xprop
    - xorg-xrandr
    - xorg-xrdb
    - xorg-xrefresh
    - xorg-xset
    - xorg-xsetroot
    - xorg-xvinfo
    - xorg-xwd
    - xorg-xwininfo
    - xorg-xwud
    - xscreensaver
    - xsel
    - yaourt
    - youtube-dl
    - zd1211-firmware
    - zsh

- name: Change shell to ZSH
  sudo: true
  user: shell=/bin/zsh name={{ ansible_ssh_user }}

- name: Set up Arch specific ~/home
  file: src=~/dotfiles/home/{{ item }}
        dest=~/{{ item }}
        state=link
        force=yes
  with_items:
    - .i3

- name: Set up .config directory
  file: src=~/dotfiles/config/{{ item }}
        dest=~/.config/{{ item }}
        state=link
        force=yes
  with_items:
    - lemonbar
    - terminator
